Name: InfComs
Main: /DuncanA/InfComs/InfComs.php
Aurthor: DuncanA
Version: 1.0
API: 1.12.0
Description: Adds commands with information and action into the PocketMine-MP Server Software for Minecraft Pocket Edition.
